# Generated by Django 3.2.25 on 2024-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.AddField(
            model_name='video',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.Genre'),
        ),
    ]
